"use client";

import Link from "next/link";
import { Archive, Download, FileCheck2, FilePlus2, FileText, QrCode, Search, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useToast } from "@/contexts/ToastContext";
import { archiveDocument, createDocumentFromOrder, getDocuments, getOperationalOrders } from "@/lib/firebase/data";
import { generateBusinessPdf } from "@/lib/pdf/generate";
import { formatDate, friendlyError, money } from "@/lib/utils";
import type { BusinessDocument, DocumentType, Order } from "@/types";

const tabs: Array<"all" | DocumentType> = ["all", "quotation", "invoice", "receipt", "agreement"];
export default function DocumentsPage() {
  const { showToast } = useToast();
  const [documents, setDocuments] = useState<BusinessDocument[]>([]);
  const [orders, setOrders] = useState<Order[]>([]);
  const [tab, setTab] = useState<(typeof tabs)[number]>("all");
  const [search, setSearch] = useState("");
  const [modal, setModal] = useState(false);
  const [orderId, setOrderId] = useState("");
  const [type, setType] = useState<DocumentType>("invoice");
  const [payment, setPayment] = useState({ method: "", reference: "" });
  const [creating, setCreating] = useState(false);
  const [downloading, setDownloading] = useState("");
  const load = () => Promise.all([getDocuments(), getOperationalOrders()]).then(([docs, orderRows]) => { setDocuments(docs); setOrders(orderRows); });
  useEffect(() => { load().catch(() => { setDocuments([]); setOrders([]); }); }, []);
  const visible = useMemo(() => documents.filter((doc) => (tab === "all" || doc.type === tab) && (!search || `${doc.documentNumber} ${doc.customer.fullName} ${doc.orderNumber || ""} ${doc.verificationCode}`.toLowerCase().includes(search.toLowerCase()))), [documents, tab, search]);
  const create = async (event: React.FormEvent) => { event.preventDefault(); if (!orderId) return; setCreating(true); try { const document = await createDocumentFromOrder(orderId, type, type === "receipt" ? payment : undefined); setDocuments((items) => [document, ...items]); setModal(false); showToast(`${type} ${document.documentNumber} created with QR verification.`, "success"); } catch (cause) { showToast(friendlyError(cause), "error"); } finally { setCreating(false); } };
  const download = async (doc: BusinessDocument) => { setDownloading(doc.id); try { await generateBusinessPdf(doc); } catch { showToast("PDF generation failed. Please try again.", "error"); } finally { setDownloading(""); } };
  const archive = async (doc: BusinessDocument) => { if (!window.confirm(`Archive ${doc.documentNumber}? The record will be preserved.`)) return; try { await archiveDocument(doc.id); setDocuments((items) => items.map((item) => item.id === doc.id ? { ...item, status: "archived" } : item)); showToast("Document archived without deleting its history.", "success"); } catch (cause) { showToast(friendlyError(cause), "error"); } };
  return <div className="dashboard-stack"><section className="dashboard-section-title"><div><h2>Document center</h2><p>Quotations, invoices, receipts, agreements, PDF and QR verification.</p></div><button className="button button-primary" onClick={() => setModal(true)}><FilePlus2 size={18} /> Create from order</button></section><div className="document-kpis">{(["quotation", "invoice", "receipt"] as DocumentType[]).map((item) => <article key={item}><span><FileText size={19} /></span><div><small>{item}s</small><strong>{documents.filter((doc) => doc.type === item).length}</strong></div></article>)}</div><section className="dashboard-panel document-center"><div className="document-toolbar"><div className="filter-scroll">{tabs.map((item) => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item === "all" ? "All documents" : `${item}s`}</button>)}</div><label className="search-field"><Search size={17} /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Number, customer, order or verification" /></label></div>{visible.length ? <div className="admin-document-table"><div className="table-head"><span>Document</span><span>Customer</span><span>Reference</span><span>Total</span><span>Status</span><span>Actions</span></div>{visible.map((doc) => <article key={doc.id}><span><i><FileCheck2 size={18} /></i><span><strong>{doc.documentNumber}</strong><small>{doc.type} · {formatDate(doc.createdAt)}</small></span></span><span>{doc.customer.fullName}<small>{doc.customer.phone}</small></span><span>{doc.orderNumber || "Standalone"}<small>{doc.verificationCode}</small></span><strong>{money(doc.total)}</strong><span className="document-status">{doc.status}</span><div><Link className="icon-button" href={`/verify/${doc.verificationCode}`} title="Verify"><QrCode size={18} /></Link><button className="icon-button" onClick={() => download(doc)} title="Download PDF" disabled={downloading === doc.id}>{downloading === doc.id ? <i className="mini-loader" /> : <Download size={18} />}</button><button className="icon-button" title="Archive without deleting history" onClick={() => archive(doc)} disabled={doc.status === "archived"}><Archive size={18} /></button></div></article>)}</div> : <div className="empty-state compact"><span className="empty-icon"><FileText size={25} /></span><h3>No matching documents</h3><p>Create an official document from an order or adjust the filters.</p></div>}</section>
    {modal && <div className="modal-layer"><button className="modal-scrim" onClick={() => setModal(false)} aria-label="Close" /><div className="record-modal small-modal"><header><div><span className="eyebrow">Traceable document chain</span><h2>Create from order</h2></div><button className="icon-button" onClick={() => setModal(false)}><X size={20} /></button></header><form onSubmit={create}><label className="field"><span>Document type</span><select value={type} onChange={(e) => setType(e.target.value as DocumentType)}><option value="quotation">Quotation</option><option value="invoice">Invoice</option><option value="receipt">Receipt</option><option value="agreement">Signed agreement</option></select></label><label className="field"><span>Source order</span><select value={orderId} onChange={(e) => setOrderId(e.target.value)} required><option value="">Select an order</option>{orders.map((order) => <option value={order.id} key={order.id}>{order.orderNumber} · {order.customer.fullName} · {money(order.total)}</option>)}</select></label>{type === "receipt" && <div className="form-grid"><label className="field"><span>Payment method *</span><input value={payment.method} onChange={(e) => setPayment({ ...payment, method: e.target.value })} placeholder="Cash, transfer…" required /></label><label className="field"><span>Payment reference *</span><input value={payment.reference} onChange={(e) => setPayment({ ...payment, reference: e.target.value })} placeholder="Transaction or cash reference" required /></label></div>}<div className="document-chain-preview"><span>Order</span><i>→</i><span>{type}</span><i>→</i><span>PDF</span><i>→</i><span>QR</span></div><p className="modal-help">The secure function snapshots the transaction, allocates a unique number and creates a public verification record.</p><div className="modal-actions"><button type="button" className="button button-ghost" onClick={() => setModal(false)}>Cancel</button><button className="button button-primary" disabled={creating || !orderId || (type === "receipt" && (!payment.method || !payment.reference))}>{creating ? <><i className="button-spinner" /> Creating…</> : "Create official document"}</button></div></form></div></div>}
  </div>;
}
