"use client";

import Link from "next/link";
import { ArrowRight, Boxes, CircleAlert, Egg, FileText, Milk, PackageCheck, PackageOpen, PawPrint, TrendingUp, UsersRound } from "lucide-react";
import { useEffect, useState } from "react";
import { StatusBadge } from "@/components/ui/StatusBadge";
import { getCollection, getDocuments, getOperationalOrders, getUsers } from "@/lib/firebase/data";
import { formatDate, money } from "@/lib/utils";
import type { BusinessDocument, Order, UserProfile } from "@/types";

type Row = Record<string, unknown> & { id: string; archived?: boolean; createdAt?: never };

export default function AdminDashboardPage() {
  const [data, setData] = useState<{ orders: Order[]; users: UserProfile[]; animals: Row[]; milk: Row[]; eggs: Row[]; inventory: Row[]; documents: BusinessDocument[] } | null>(null);
  useEffect(() => { Promise.all([getOperationalOrders(), getUsers(), getCollection<Row>("animals"), getCollection<Row>("milkProduction"), getCollection<Row>("eggProduction"), getCollection<Row>("inventory"), getDocuments()]).then(([orders, users, animals, milk, eggs, inventory, documents]) => setData({ orders, users, animals, milk, eggs, inventory, documents })).catch(() => setData({ orders: [], users: [], animals: [], milk: [], eggs: [], inventory: [], documents: [] })); }, []);
  const completed = data?.orders.filter((order) => ["delivered", "completed"].includes(order.status)) || [];
  const sales = completed.reduce((sum, order) => sum + order.total, 0);
  const pending = data?.orders.filter((order) => ["pending", "confirmed", "preparing", "ready"].includes(order.status)) || [];
  const livestock = data?.animals.filter((item) => !item.archived) || [];
  const milkTotal = data?.milk.reduce((sum, row) => sum + Number(row.totalProduction || 0), 0) || 0;
  const eggTotal = data?.eggs.reduce((sum, row) => sum + Number(row.eggsCollected || 0), 0) || 0;
  const lowStock = data?.inventory.filter((row) => !row.archived && Number(row.quantity) <= Number(row.lowStockThreshold)) || [];
  return <div className="dashboard-stack"><section className="admin-command-banner"><div><span>Business overview</span><h2>Everything that matters, connected.</h2><p>Live totals below are derived from Firebase records — never placeholder statistics.</p></div><Link href="/admin/reports" className="button button-light"><TrendingUp size={18} /> Open reports</Link></section>
    <section className="stat-grid admin-stats"><article><span><TrendingUp size={20} /></span><div><small>Completed sales</small><strong>{data ? money(sales) : "—"}</strong></div></article><article><span><PackageCheck size={20} /></span><div><small>Total orders</small><strong>{data ? data.orders.length : "—"}</strong></div></article><article><span><UsersRound size={20} /></span><div><small>Customers</small><strong>{data ? data.users.filter((u) => u.role === "user").length : "—"}</strong></div></article><article><span><UsersRound size={20} /></span><div><small>Staff</small><strong>{data ? data.users.filter((u) => u.role === "staff").length : "—"}</strong></div></article><article><span><PawPrint size={20} /></span><div><small>Livestock records</small><strong>{data ? livestock.length : "—"}</strong></div></article><article><span><Milk size={20} /></span><div><small>Milk recorded</small><strong>{data ? `${milkTotal}L` : "—"}</strong></div></article><article><span><Egg size={20} /></span><div><small>Eggs recorded</small><strong>{data ? eggTotal : "—"}</strong></div></article><article className={lowStock.length ? "warning" : ""}><span><Boxes size={20} /></span><div><small>Low stock</small><strong>{data ? lowStock.length : "—"}</strong></div></article></section>
    <div className="dashboard-two-columns admin-columns"><section className="dashboard-panel"><div className="panel-head"><div><h2>Orders needing attention</h2><p>Pending and preparing transactions.</p></div><Link href="/admin/orders">Manage <ArrowRight size={16} /></Link></div>{pending.length ? <div className="admin-order-table"><div className="table-head"><span>Order</span><span>Customer</span><span>Total</span><span>Status</span></div>{pending.slice(0, 6).map((order) => <Link href="/admin/orders" key={order.id}><span><strong>{order.orderNumber}</strong><small>{formatDate(order.createdAt)}</small></span><span>{order.customer.fullName}<small>{order.delivery.location}</small></span><strong>{money(order.total)}</strong><StatusBadge status={order.status} /></Link>)}</div> : <p className="panel-empty-copy"><PackageCheck size={20} /> No active orders need attention.</p>}</section>
    <section className="dashboard-panel"><div className="panel-head"><div><h2>Business documents</h2><p>Official traceable records.</p></div><Link href="/admin/documents">Open center</Link></div><div className="document-overview-list"><article><span><FileText size={19} /></span><p><strong>{data ? data.documents.filter((d) => d.type === "quotation").length : "—"}</strong><small>Quotations</small></p></article><article><span><FileText size={19} /></span><p><strong>{data ? data.documents.filter((d) => d.type === "invoice").length : "—"}</strong><small>Invoices</small></p></article><article><span><FileText size={19} /></span><p><strong>{data ? data.documents.filter((d) => d.type === "receipt").length : "—"}</strong><small>Receipts</small></p></article></div><Link href="/admin/documents" className="button button-secondary button-full">Create or verify document</Link></section></div>
    <section className="dashboard-panel quick-management"><div className="panel-head"><div><h2>Quick management</h2><p>Jump into a business area.</p></div></div><div><Link href="/admin/products"><span><PackageOpen size={20} /></span><strong>Products</strong><small>Prices &amp; availability</small><ArrowRight size={16} /></Link><Link href="/admin/users"><span><UsersRound size={20} /></span><strong>People</strong><small>Roles &amp; accounts</small><ArrowRight size={16} /></Link><Link href="/admin/farm"><span><PawPrint size={20} /></span><strong>Farm</strong><small>Production &amp; livestock</small><ArrowRight size={16} /></Link><Link href="/admin/documents"><span><FileText size={20} /></span><strong>Documents</strong><small>PDF &amp; QR records</small><ArrowRight size={16} /></Link></div></section>
    {data && !data.orders.length && !data.users.length && <div className="dashboard-data-note"><CircleAlert size={17} /> Firebase is connected, but no business records are currently visible to this account. Use the setup actions in Products and Settings.</div>}
  </div>;
}
