"use client";

import { Archive, CalendarDays, CircleAlert, ClipboardPlus, CloudUpload, Plus, TriangleAlert, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useAuth } from "@/contexts/AuthContext";
import { useToast } from "@/contexts/ToastContext";
import { useCloudinaryUpload } from "@/hooks/useCloudinaryUpload";
import { addFarmRecord, archiveFarmRecord, getCollection } from "@/lib/firebase/data";
import { formatDate, friendlyError } from "@/lib/utils";

export type OperationMode = "animals" | "milk" | "eggs" | "inventory" | "activities" | "crops" | "feed" | "health" | "equipment";

const configs = {
  animals: { collection: "animals", title: "Animals", description: "Cattle, pigs and chicken records with accountable traceability." },
  milk: { collection: "milkProduction", title: "Milk production", description: "Morning, evening, sold, remaining and wasted litres." },
  eggs: { collection: "eggProduction", title: "Egg production", description: "Collected, sold, damaged and remaining egg counts." },
  inventory: { collection: "inventory", title: "Inventory", description: "Current farm stock with low-stock thresholds." },
  activities: { collection: "farmActivities", title: "Farm activities", description: "Feeding, cleaning, inspections, repairs and general work." },
  crops: { collection: "crops", title: "Crops & seeds", description: "Seed, planting, harvest and plot records for the growing season." },
  feed: { collection: "feed", title: "Feed management", description: "Feed stock, suppliers, usage and reorder alerts for each animal group." },
  health: { collection: "animalHealth", title: "Animal health", description: "Vaccinations, treatments, medication and veterinary records." },
  equipment: { collection: "equipment", title: "Farm equipment", description: "Tractors, pumps, fencing, tools and machinery with maintenance tracking." },
} as const;

const empty = {
  animals: { species: "cattle", animalId: "", tagNumber: "", name: "", breed: "", sex: "female", dateOfBirth: "", photo: "", weight: "", healthStatus: "healthy", location: "", currentStatus: "active", notes: "" },
  milk: { date: new Date().toISOString().slice(0, 10), morningProduction: "", eveningProduction: "", sold: "", wasted: "", price: "16", customer: "", orderId: "" },
  eggs: { date: new Date().toISOString().slice(0, 10), eggsCollected: "", eggsSold: "", eggsDamaged: "", price: "", customer: "", orderId: "" },
  inventory: { product: "", category: "Farm supplies", quantity: "", unit: "units", stockIn: "0", stockOut: "0", lowStockThreshold: "5", location: "", reason: "Stock count" },
  activities: { activity: "Feeding", date: new Date().toISOString().slice(0, 10), time: new Date().toTimeString().slice(0, 5), notes: "", location: "" },
  crops: { seedName: "", cropType: "Maize", variety: "", quantity: "", unit: "kg", purchaseDate: "", supplier: "", cost: "", storageLocation: "", plantingDate: "", expectedHarvest: "", actualHarvest: "", fieldOrPlot: "", currentStock: "", notes: "" },
  feed: { feedType: "", quantity: "", unit: "kg", supplier: "", purchasePrice: "", purchaseDate: "", currentStock: "", usage: "", animalGroup: "All groups", reorderLevel: "0", notes: "" },
  health: { animalId: "", recordType: "Vaccination", medication: "", date: new Date().toISOString().slice(0, 10), nextDate: "", animalAffected: "", notes: "", photo: "" },
  equipment: { equipmentName: "", category: "Tools", photo: "", purchaseDate: "", condition: "Good", maintenanceDueDate: "", assignedStaff: "", notes: "" },
};

type GenericRecord = Record<string, unknown> & { id: string; createdAt?: unknown; createdBy?: string; archived?: boolean };

function numericKeys(mode: OperationMode) {
  switch (mode) {
    case "animals": return ["weight"];
    case "crops": return ["quantity", "cost", "currentStock"];
    case "feed": return ["quantity", "purchasePrice", "currentStock", "usage", "reorderLevel"];
    case "inventory": return ["quantity", "stockIn", "stockOut", "lowStockThreshold"];
    case "milk": return ["morningProduction", "eveningProduction", "sold", "wasted", "price"];
    case "eggs": return ["eggsCollected", "eggsSold", "eggsDamaged", "price"];
    default: return [];
  }
}

export function OperationsModule({ mode }: { mode: OperationMode }) {
  const config = configs[mode];
  const { user } = useAuth();
  const { showToast } = useToast();
  const { upload, uploading, progress } = useCloudinaryUpload();
  const [records, setRecords] = useState<GenericRecord[]>([]);
  const [form, setForm] = useState<Record<string, string>>({ ...empty[mode] });
  const [open, setOpen] = useState(false);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");

  const load = () => { setLoading(true); getCollection<GenericRecord>(config.collection).then((data) => setRecords(data.filter((item) => !item.archived))).catch(() => setRecords([])).finally(() => setLoading(false)); };
  useEffect(load, [config.collection]);
  const update = (key: string, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const uploadPhoto = async (file?: File, folder: "animals" | "gallery" | "products" | "documents" | "profiles" = "animals") => {
    if (!file) return;
    try { const result = await upload(file, folder); update("photo", result.url); showToast("Photo uploaded securely.", "success"); }
    catch (cause) { setError(cause instanceof Error ? cause.message : friendlyError(cause)); }
  };

  const payload = useMemo(() => {
    if (mode === "milk") { const morning = Number(form.morningProduction || 0); const evening = Number(form.eveningProduction || 0); const sold = Number(form.sold || 0); const wasted = Number(form.wasted || 0); const total = morning + evening; return { ...form, morningProduction: morning, eveningProduction: evening, totalProduction: total, sold, wasted, remaining: Math.max(0, total - sold - wasted), price: Number(form.price || 0), dateTime: new Date(`${form.date}T12:00:00`).toISOString() }; }
    if (mode === "eggs") { const collected = Number(form.eggsCollected || 0); const sold = Number(form.eggsSold || 0); const damaged = Number(form.eggsDamaged || 0); return { ...form, eggsCollected: collected, eggsSold: sold, eggsDamaged: damaged, eggsRemaining: Math.max(0, collected - sold - damaged), price: Number(form.price || 0), dateTime: new Date(`${form.date}T12:00:00`).toISOString() }; }
    const keys = numericKeys(mode);
    const next: Record<string, unknown> = { ...form };
    for (const key of keys) next[key] = form[key] === "" ? null : Number(form[key]);
    if (mode === "activities") return { ...next, occurredAt: new Date(`${form.date}T${form.time || "00:00"}:00`).toISOString() };
    if (mode === "crops") return { ...next, occurredAt: new Date(`${form.plantingDate || form.purchaseDate || form.date || new Date().toISOString().slice(0, 10)}T12:00:00`).toISOString() };
    if (mode === "feed") return { ...next, occurredAt: new Date(`${form.purchaseDate || form.date || new Date().toISOString().slice(0, 10)}T12:00:00`).toISOString() };
    if (mode === "health") return { ...next, occurredAt: new Date(`${form.date}T12:00:00`).toISOString() };
    if (mode === "equipment") return { ...next, occurredAt: new Date(`${form.purchaseDate || form.date || new Date().toISOString().slice(0, 10)}T12:00:00`).toISOString() };
    return next;
  }, [form, mode]);

  const save = async (event: React.FormEvent) => {
    event.preventDefault(); setError("");
    const requiredMap: Record<OperationMode, string[]> = {
      animals: ["animalId", "tagNumber", "breed", "location"], inventory: ["product", "quantity", "unit"], activities: ["activity", "date", "notes"],
      milk: ["date", "morningProduction", "eveningProduction"], eggs: ["date", "eggsCollected"], crops: ["seedName", "quantity", "unit"],
      feed: ["feedType", "quantity", "unit"], health: ["animalId", "recordType", "date"], equipment: ["equipmentName", "category"],
    };
    const required = requiredMap[mode];
    if (required.some((key) => !form[key])) { setError("Complete all required fields before saving."); return; }
    if (mode === "milk" && Number(form.sold || 0) + Number(form.wasted || 0) > Number(form.morningProduction || 0) + Number(form.eveningProduction || 0)) { setError("Sold and wasted milk cannot exceed total production."); return; }
    if (mode === "eggs" && Number(form.eggsSold || 0) + Number(form.eggsDamaged || 0) > Number(form.eggsCollected || 0)) { setError("Sold and damaged eggs cannot exceed eggs collected."); return; }
    setSaving(true);
    try {
      await addFarmRecord(config.collection, payload);
      if (mode === "inventory") await addFarmRecord("inventoryTransactions", { product: form.product, unit: form.unit, stockIn: Number(form.stockIn || 0), stockOut: Number(form.stockOut || 0), currentBalance: Number(form.quantity || 0), reason: form.reason });
      showToast(`${config.title} record saved.`, "success"); setForm({ ...empty[mode] }); setOpen(false); load();
    }
    catch (cause) { setError(friendlyError(cause)); }
    finally { setSaving(false); }
  };

  const archive = async (id: string) => { if (!window.confirm("Archive this record? It will stay in business history.")) return; try { await archiveFarmRecord(config.collection, id); setRecords((current) => current.filter((item) => item.id !== id)); showToast("Record archived.", "success"); } catch (cause) { showToast(friendlyError(cause), "error"); } };

  const isLow = (record: GenericRecord, mode: OperationMode) => {
    if (mode === "inventory") return Number(record.quantity) <= Number(record.lowStockThreshold);
    if (mode === "feed") return Number(record.currentStock) <= Number(record.reorderLevel);
    return false;
  };
  const feedLow = records.filter((record) => Number(record.currentStock) <= Number(record.reorderLevel));

  return <div className="dashboard-stack"><section className="dashboard-section-title"><div><h2>{config.title}</h2><p>{config.description}</p></div><button className="button button-primary" onClick={() => setOpen(true)}><Plus size={18} /> Add record</button></section>
    {mode === "milk" && <div className="production-summary"><article><small>Recorded production</small><strong>{records.reduce((sum, item) => sum + Number(item.totalProduction || 0), 0)}L</strong></article><article><small>Recorded sold</small><strong>{records.reduce((sum, item) => sum + Number(item.sold || 0), 0)}L</strong></article><article><small>Recorded remaining</small><strong>{records.reduce((sum, item) => sum + Number(item.remaining || 0), 0)}L</strong></article></div>}
    {mode === "eggs" && <div className="production-summary"><article><small>Recorded collected</small><strong>{records.reduce((sum, item) => sum + Number(item.eggsCollected || 0), 0)}</strong></article><article><small>Recorded sold</small><strong>{records.reduce((sum, item) => sum + Number(item.eggsSold || 0), 0)}</strong></article><article><small>Recorded remaining</small><strong>{records.reduce((sum, item) => sum + Number(item.eggsRemaining || 0), 0)}</strong></article></div>}
    {mode === "feed" && <div className="production-summary"><article><small>Feed types tracked</small><strong>{records.length}</strong></article><article className={feedLow.length ? "warning" : ""}><small>Low stock</small><strong>{feedLow.length}</strong></article></div>}
    {mode === "crops" && <div className="production-summary"><article><small>Plots tracked</small><strong>{records.length}</strong></article><article><small>Total seed in stock</small><strong>{records.reduce((sum, item) => sum + Number(item.currentStock || 0), 0)} {String(records[0]?.unit || "")}</strong></article></div>}
    <section className="dashboard-panel operations-list-panel">{loading ? <div className="loading-state"><i className="loader" /> Loading records…</div> : records.length ? <div className="operations-list">{records.map((record) => <article key={record.id} className={isLow(record, mode) ? "low-stock" : ""}><span className="operation-record-icon"><ClipboardPlus size={19} /></span><div className="operation-main"><small>{recordDate(record, mode)}</small><strong>{recordTitle(record, mode)}</strong><p>{recordDescription(record, mode)}</p></div><div className="operation-values">{recordValues(record, mode)}</div><span className="record-author">Recorded by<br /><strong>{record.createdBy === user?.uid ? "You" : "Team member"}</strong></span><button className="icon-button" onClick={() => archive(record.id)} title="Archive record"><Archive size={17} /></button></article>)}</div> : <div className="empty-state compact"><span className="empty-icon"><ClipboardPlus size={25} /></span><h3>No records yet</h3><p>Use “Add record” to enter the first verified farm record.</p></div>}</section>
    {mode === "feed" && feedLow.length > 0 && <section className="operational-alert"><TriangleAlert size={20} /><div><strong>Feed stock: Low</strong><p>{feedLow.slice(0, 3).map((item) => `${String(item.feedType)} (${String(item.currentStock)} ${String(item.unit)})`).join(", ")}{feedLow.length > 3 ? ` and ${feedLow.length - 3} more` : ""}</p></div></section>}
    {open && <div className="modal-layer"><button className="modal-scrim" onClick={() => setOpen(false)} aria-label="Close form" /><div className="record-modal" role="dialog" aria-modal="true"><header><div><span className="eyebrow">New farm record</span><h2>Add {config.title.toLowerCase()}</h2></div><button className="icon-button" onClick={() => setOpen(false)}><X size={20} /></button></header><form onSubmit={save}>{mode === "animals" && <AnimalFields form={form} update={update} uploadPhoto={(file) => uploadPhoto(file, "animals")} uploading={uploading} progress={progress} />}{mode === "milk" && <MilkFields form={form} update={update} />}{mode === "eggs" && <EggFields form={form} update={update} />}{mode === "inventory" && <InventoryFields form={form} update={update} />}{mode === "activities" && <ActivityFields form={form} update={update} />}{mode === "crops" && <CropFields form={form} update={update} />}{mode === "feed" && <FeedFields form={form} update={update} />}{mode === "health" && <HealthFields form={form} update={update} uploadPhoto={(file) => uploadPhoto(file, "animals")} uploading={uploading} progress={progress} />}{mode === "equipment" && <EquipmentFields form={form} update={update} uploadPhoto={(file) => uploadPhoto(file, "gallery")} uploading={uploading} progress={progress} />}{error && <div className="form-alert error"><CircleAlert size={17} /> {error}</div>}<div className="modal-actions"><button type="button" className="button button-ghost" onClick={() => setOpen(false)}>Cancel</button><button className="button button-primary" disabled={saving}>{saving ? <><i className="button-spinner" /> Saving…</> : "Save traceable record"}</button></div></form></div></div>}
  </div>;
}

function Field({ label, name, form, update, type = "text", required = false, children }: { label: string; name: string; form: Record<string, string>; update: (key: string, value: string) => void; type?: string; required?: boolean; children?: React.ReactNode }) { return <label className="field"><span>{label}{required && " *"}</span>{children || <input type={type} value={form[name] || ""} onChange={(e) => update(name, e.target.value)} required={required} />}</label>; }
function PhotoUpload({ form, uploadPhoto, uploading, progress, label = "Photo" }: { form: Record<string, string>; uploadPhoto: (file?: File) => Promise<void>; uploading: boolean; progress: number; label?: string }) { return <label className="field field-full"><span>{label}</span><span className="button button-secondary file-button"><CloudUpload size={17} /> {uploading ? `Uploading ${progress}%` : form.photo ? "Replace uploaded photo" : "Upload photo"}<input type="file" accept="image/*" onChange={(e) => uploadPhoto(e.target.files?.[0])} disabled={uploading} /></span>{form.photo && <small>Photo stored securely.</small>}</label>; }
function AnimalFields({ form, update, uploadPhoto, uploading, progress }: { form: Record<string, string>; update: (k: string, v: string) => void; uploadPhoto: (file?: File) => Promise<void>; uploading: boolean; progress: number }) { return <div className="form-grid"><Field label="Species" name="species" form={form} update={update}><select value={form.species} onChange={(e) => update("species", e.target.value)}><option value="cattle">Cattle</option><option value="pig">Pig</option><option value="chicken">Chicken / flock</option></select></Field><Field label="Animal / flock ID" name="animalId" form={form} update={update} required /><Field label="Tag number" name="tagNumber" form={form} update={update} required /><Field label="Name" name="name" form={form} update={update} /><Field label="Breed" name="breed" form={form} update={update} required /><Field label="Sex" name="sex" form={form} update={update}><select value={form.sex} onChange={(e) => update("sex", e.target.value)}><option value="female">Female</option><option value="male">Male</option><option value="mixed">Mixed flock</option></select></Field><Field label="Date of birth" name="dateOfBirth" type="date" form={form} update={update} /><Field label="Weight (kg)" name="weight" type="number" form={form} update={update} /><Field label="Health" name="healthStatus" form={form} update={update}><select value={form.healthStatus} onChange={(e) => update("healthStatus", e.target.value)}><option value="healthy">Healthy</option><option value="sick">Sick</option><option value="injured">Injured</option><option value="recovering">Recovering</option></select></Field><Field label="Location" name="location" form={form} update={update} required /><PhotoUpload form={form} uploadPhoto={uploadPhoto} uploading={uploading} progress={progress} label="Animal photo" /><label className="field field-full"><span>Notes</span><textarea rows={3} value={form.notes} onChange={(e) => update("notes", e.target.value)} /></label></div>; }
function MilkFields({ form, update }: { form: Record<string, string>; update: (k: string, v: string) => void }) { const total = Number(form.morningProduction || 0) + Number(form.eveningProduction || 0); const remaining = Math.max(0, total - Number(form.sold || 0) - Number(form.wasted || 0)); return <><div className="form-grid"><Field label="Date" name="date" type="date" form={form} update={update} required /><Field label="Morning litres" name="morningProduction" type="number" form={form} update={update} required /><Field label="Evening litres" name="eveningProduction" type="number" form={form} update={update} required /><Field label="Litres sold" name="sold" type="number" form={form} update={update} /><Field label="Spoiled / wasted" name="wasted" type="number" form={form} update={update} /><Field label="Price per litre" name="price" type="number" form={form} update={update} /><Field label="Customer (if sold)" name="customer" form={form} update={update} /><Field label="Order reference" name="orderId" form={form} update={update} /></div><div className="calculated-row"><span>Total <strong>{total}L</strong></span><span>Remaining <strong>{remaining}L</strong></span></div></>; }
function EggFields({ form, update }: { form: Record<string, string>; update: (k: string, v: string) => void }) { const remaining = Math.max(0, Number(form.eggsCollected || 0) - Number(form.eggsSold || 0) - Number(form.eggsDamaged || 0)); return <><div className="form-grid"><Field label="Date" name="date" type="date" form={form} update={update} required /><Field label="Eggs collected" name="eggsCollected" type="number" form={form} update={update} required /><Field label="Eggs sold" name="eggsSold" type="number" form={form} update={update} /><Field label="Eggs damaged" name="eggsDamaged" type="number" form={form} update={update} /><Field label="Sales price" name="price" type="number" form={form} update={update} /><Field label="Customer (if sold)" name="customer" form={form} update={update} /><Field label="Order reference" name="orderId" form={form} update={update} /></div><div className="calculated-row"><span>Remaining <strong>{remaining} eggs</strong></span></div></>; }
function InventoryFields({ form, update }: { form: Record<string, string>; update: (k: string, v: string) => void }) { return <div className="form-grid"><Field label="Product / item" name="product" form={form} update={update} required /><Field label="Category" name="category" form={form} update={update}><select value={form.category} onChange={(e) => update("category", e.target.value)}><option>Farm supplies</option><option>Feed</option><option>Milk</option><option>Eggs</option><option>Packaging</option><option>Other</option></select></Field><Field label="Current quantity" name="quantity" type="number" form={form} update={update} required /><Field label="Unit" name="unit" form={form} update={update} required /><Field label="Stock in" name="stockIn" type="number" form={form} update={update} /><Field label="Stock out" name="stockOut" type="number" form={form} update={update} /><Field label="Low-stock warning at" name="lowStockThreshold" type="number" form={form} update={update} /><Field label="Storage location" name="location" form={form} update={update} /><Field label="Reason / reference" name="reason" form={form} update={update} /></div>; }
function ActivityFields({ form, update }: { form: Record<string, string>; update: (k: string, v: string) => void }) { return <div className="form-grid"><Field label="Activity" name="activity" form={form} update={update}><select value={form.activity} onChange={(e) => update("activity", e.target.value)}>{["Feeding", "Cleaning", "Vaccination", "Animal inspection", "Milk collection", "Egg collection", "Stock arrival", "Stock usage", "Repairs", "General activity"].map((value) => <option key={value}>{value}</option>)}</select></Field><Field label="Date" name="date" type="date" form={form} update={update} required /><Field label="Time" name="time" type="time" form={form} update={update} /><Field label="Location" name="location" form={form} update={update} /><label className="field field-full"><span>Notes *</span><textarea rows={4} value={form.notes} onChange={(e) => update("notes", e.target.value)} required /></label></div>; }
function CropFields({ form, update }: { form: Record<string, string>; update: (k: string, v: string) => void }) { return <div className="form-grid"><Field label="Seed name *" name="seedName" form={form} update={update} required /><Field label="Crop type" name="cropType" form={form} update={update}><select value={form.cropType} onChange={(e) => update("cropType", e.target.value)}>{["Maize", "Beans", "Vegetables", "Fruit", "Fodder", "Other"].map((value) => <option key={value}>{value}</option>)}</select></Field><Field label="Variety" name="variety" form={form} update={update} /><Field label="Quantity" name="quantity" type="number" form={form} update={update} required /><Field label="Unit" name="unit" form={form} update={update} required /><Field label="Current stock" name="currentStock" type="number" form={form} update={update} /><Field label="Purchase date" name="purchaseDate" type="date" form={form} update={update} /><Field label="Supplier" name="supplier" form={form} update={update} /><Field label="Cost (E)" name="cost" type="number" form={form} update={update} /><Field label="Storage location" name="storageLocation" form={form} update={update} /><Field label="Planting date" name="plantingDate" type="date" form={form} update={update} /><Field label="Expected harvest" name="expectedHarvest" type="date" form={form} update={update} /><Field label="Actual harvest" name="actualHarvest" type="date" form={form} update={update} /><Field label="Field / plot" name="fieldOrPlot" form={form} update={update} /><label className="field field-full"><span>Notes</span><textarea rows={3} value={form.notes} onChange={(e) => update("notes", e.target.value)} /></label></div>; }
function FeedFields({ form, update }: { form: Record<string, string>; update: (k: string, v: string) => void }) { return <div className="form-grid"><Field label="Feed type *" name="feedType" form={form} update={update} required /><Field label="Quantity" name="quantity" type="number" form={form} update={update} required /><Field label="Unit" name="unit" form={form} update={update} required /><Field label="Current stock" name="currentStock" type="number" form={form} update={update} /><Field label="Usage to date" name="usage" type="number" form={form} update={update} /><Field label="Animal group" name="animalGroup" form={form} update={update}><select value={form.animalGroup} onChange={(e) => update("animalGroup", e.target.value)}>{["All groups", "Cattle", "Pigs", "Chickens", "Calves"].map((value) => <option key={value}>{value}</option>)}</select></Field><Field label="Supplier" name="supplier" form={form} update={update} /><Field label="Purchase price (E)" name="purchasePrice" type="number" form={form} update={update} /><Field label="Purchase date" name="purchaseDate" type="date" form={form} update={update} /><Field label="Reorder level" name="reorderLevel" type="number" form={form} update={update} /><label className="field field-full"><span>Notes</span><textarea rows={3} value={form.notes} onChange={(e) => update("notes", e.target.value)} /></label></div>; }
function HealthFields({ form, update, uploadPhoto, uploading, progress }: { form: Record<string, string>; update: (k: string, v: string) => void; uploadPhoto: (file?: File) => Promise<void>; uploading: boolean; progress: number }) { return <div className="form-grid"><Field label="Animal / flock ID *" name="animalId" form={form} update={update} required /><Field label="Record type" name="recordType" form={form} update={update}><select value={form.recordType} onChange={(e) => update("recordType", e.target.value)}>{["Vaccination", "Treatment", "Medication", "Veterinary visit", "Observation", "Upcoming treatment"].map((value) => <option key={value}>{value}</option>)}</select></Field><Field label="Date *" name="date" type="date" form={form} update={update} required /><Field label="Next / upcoming date" name="nextDate" type="date" form={form} update={update} /><Field label="Medication / vaccine" name="medication" form={form} update={update} /><Field label="Animal affected" name="animalAffected" form={form} update={update} /><PhotoUpload form={form} uploadPhoto={uploadPhoto} uploading={uploading} progress={progress} label="Supporting document / photo" /><label className="field field-full"><span>Notes</span><textarea rows={3} value={form.notes} onChange={(e) => update("notes", e.target.value)} /></label></div>; }
function EquipmentFields({ form, update, uploadPhoto, uploading, progress }: { form: Record<string, string>; update: (k: string, v: string) => void; uploadPhoto: (file?: File) => Promise<void>; uploading: boolean; progress: number }) { return <div className="form-grid"><Field label="Equipment name *" name="equipmentName" form={form} update={update} required /><Field label="Category" name="category" form={form} update={update}><select value={form.category} onChange={(e) => update("category", e.target.value)}>{["Tractor", "Pump", "Fencing equipment", "Tool", "Machinery", "Vehicle", "Other"].map((value) => <option key={value}>{value}</option>)}</select></Field><Field label="Condition" name="condition" form={form} update={update}><select value={form.condition} onChange={(e) => update("condition", e.target.value)}>{["Good", "Fair", "Needs repair", "Out of service"].map((value) => <option key={value}>{value}</option>)}</select></Field><Field label="Purchase date" name="purchaseDate" type="date" form={form} update={update} /><Field label="Maintenance due" name="maintenanceDueDate" type="date" form={form} update={update} /><Field label="Assigned staff" name="assignedStaff" form={form} update={update} /><PhotoUpload form={form} uploadPhoto={uploadPhoto} uploading={uploading} progress={progress} label="Equipment photo" /><label className="field field-full"><span>Notes</span><textarea rows={3} value={form.notes} onChange={(e) => update("notes", e.target.value)} /></label></div>; }
function recordDate(record: GenericRecord, mode: OperationMode) { if (mode === "feed") return String(record.purchaseDate || record.date || (record.createdAt ? formatDate(record.createdAt as never, true) : mode)); if (mode === "crops") return String(record.plantingDate || record.purchaseDate || record.date || (record.createdAt ? formatDate(record.createdAt as never, true) : mode)); if (mode === "equipment") return String(record.purchaseDate || record.date || (record.createdAt ? formatDate(record.createdAt as never, true) : mode)); return String(record.date || (record.createdAt ? formatDate(record.createdAt as never, true) : mode)); }
function recordTitle(record: GenericRecord, mode: OperationMode) { if (mode === "animals") return `${String(record.species)} · ${String(record.animalId)}`; if (mode === "milk") return `${record.totalProduction || 0}L total milk`; if (mode === "eggs") return `${record.eggsCollected || 0} eggs collected`; if (mode === "inventory") return String(record.product); if (mode === "crops") return `${String(record.seedName)}${record.variety ? ` · ${String(record.variety)}` : ""}`; if (mode === "feed") return String(record.feedType); if (mode === "health") return `${String(record.recordType)} · ${String(record.animalId)}`; if (mode === "equipment") return String(record.equipmentName); return String(record.activity); }
function recordDescription(record: GenericRecord, mode: OperationMode) { if (mode === "animals") return `${record.breed || "Breed not set"} · ${record.healthStatus || "Health not set"} · ${record.location || ""}`; if (mode === "milk") return `Morning ${record.morningProduction || 0}L · Evening ${record.eveningProduction || 0}L · Wasted ${record.wasted || 0}L`; if (mode === "eggs") return `Sold ${record.eggsSold || 0} · Damaged ${record.eggsDamaged || 0}`; if (mode === "inventory") return `${record.category || ""} · ${record.location || "Location not set"}`; if (mode === "crops") return `${record.cropType || "Crop not set"} · ${record.fieldOrPlot || "Plot not set"} · ${record.supplier || ""}`; if (mode === "feed") return `${record.animalGroup || "All groups"} · ${record.supplier || "Supplier not set"}`; if (mode === "health") return `${record.medication || "No medication listed"} · ${record.animalAffected || ""}`; if (mode === "equipment") return `${record.category || ""} · ${record.condition || "Condition not set"} · ${record.assignedStaff || ""}`; return `${record.location || "Farm"} · ${record.notes || "No notes"}`; }
function recordValues(record: GenericRecord, mode: OperationMode) { if (mode === "animals") return <><small>Weight</small><strong>{record.weight ? `${record.weight}kg` : "—"}</strong></>; if (mode === "milk") return <><small>Remaining</small><strong>{String(record.remaining || 0)}L</strong></>; if (mode === "eggs") return <><small>Remaining</small><strong>{String(record.eggsRemaining || 0)}</strong></>; if (mode === "inventory") return <><small>Balance</small><strong>{String(record.quantity)} {String(record.unit)}</strong>{Number(record.quantity) <= Number(record.lowStockThreshold) && <em>Low stock</em>}</>; if (mode === "crops") return <><small>Stock</small><strong>{String(record.currentStock ?? record.quantity)} {String(record.unit)}</strong></>; if (mode === "feed") return <><small>Stock</small><strong>{String(record.currentStock)} {String(record.unit)}</strong>{Number(record.currentStock) <= Number(record.reorderLevel) && <em>Low stock</em>}</>; if (mode === "health") return <><small>Upcoming</small><strong>{record.nextDate ? String(record.nextDate) : "—"}</strong></>; if (mode === "equipment") return <><small>Maintenance due</small><strong>{record.maintenanceDueDate ? String(record.maintenanceDueDate) : "—"}</strong></>; return <><CalendarDays size={18} /><strong>{String(record.time || "")}</strong></>; }
