"use client";

import Image from "next/image";
import Link from "next/link";
import { Archive, CloudUpload, Eye, ImagePlus, Images, Plus, Settings, X } from "lucide-react";
import { useEffect, useState } from "react";
import { useCloudinaryUpload } from "@/hooks/useCloudinaryUpload";
import { useToast } from "@/contexts/ToastContext";
import { archiveGalleryItem, getCollection, saveGalleryItem } from "@/lib/firebase/data";
import { friendlyError } from "@/lib/utils";

interface GalleryRow { id: string; title: string; category: string; src: string; archived?: boolean; }
export default function ContentPage() {
  const { upload, uploading, progress } = useCloudinaryUpload();
  const { showToast } = useToast();
  const [items, setItems] = useState<GalleryRow[]>([]);
  const [modal, setModal] = useState(false);
  const [form, setForm] = useState({ title: "", category: "Farm", src: "" });
  const [saving, setSaving] = useState(false);
  const load = () => getCollection<GalleryRow>("gallery", 100).then((rows) => setItems(rows.filter((item) => !item.archived))).catch(() => setItems([]));
  useEffect(() => { void load(); }, []);
  const choose = async (file?: File) => { if (!file) return; try { const result = await upload(file, "gallery"); setForm((current) => ({ ...current, src: result.url })); } catch (cause) { showToast(cause instanceof Error ? cause.message : friendlyError(cause), "error"); } };
  const save = async (event: React.FormEvent) => { event.preventDefault(); if (!form.src) { showToast("Upload an image first.", "error"); return; } setSaving(true); try { await saveGalleryItem(form); showToast("Gallery item published.", "success"); setForm({ title: "", category: "Farm", src: "" }); setModal(false); load(); } catch (cause) { showToast(friendlyError(cause), "error"); } finally { setSaving(false); } };
  const archive = async (item: GalleryRow) => { if (!window.confirm(`Archive “${item.title}”?`)) return; try { await archiveGalleryItem(item.id); setItems((current) => current.filter((entry) => entry.id !== item.id)); showToast("Gallery item archived.", "success"); } catch (cause) { showToast(friendlyError(cause), "error"); } };
  return <div className="dashboard-stack"><section className="dashboard-section-title"><div><h2>Website content &amp; gallery</h2><p>Publish authentic farm media or clearly labelled brand visuals without code changes.</p></div><button className="button button-primary" onClick={() => setModal(true)}><Plus size={18} /> Add gallery item</button></section><div className="content-action-grid"><Link href="/admin/settings"><span><Settings size={20} /></span><div><strong>Homepage &amp; contact</strong><p>Edit the announcement, hero headline, delivery areas and business information.</p></div></Link><Link href="/gallery" target="_blank"><span><Eye size={20} /></span><div><strong>Preview public gallery</strong><p>Review the customer-facing visual journal in a new tab.</p></div></Link></div><section className="dashboard-panel"><div className="panel-head"><div><h2>Published Firebase gallery</h2><p>Local launch illustrations remain as fallbacks until real farm media is uploaded.</p></div><Images size={20} /></div>{items.length ? <div className="admin-gallery-grid">{items.map((item) => <article key={item.id}><div><Image src={item.src} alt={item.title} fill sizes="240px" /></div><span>{item.category}</span><strong>{item.title}</strong><button className="icon-button" onClick={() => archive(item)} title="Archive"><Archive size={17} /></button></article>)}</div> : <div className="empty-state compact"><span className="empty-icon"><Images size={25} /></span><h3>No uploaded gallery records</h3><p>The public gallery is currently using the clearly disclosed launch illustrations.</p><button className="button button-secondary" onClick={() => setModal(true)}><ImagePlus size={17} /> Upload first image</button></div>}</section>
    {modal && <div className="modal-layer"><button className="modal-scrim" onClick={() => setModal(false)} aria-label="Close" /><div className="record-modal small-modal"><header><div><span className="eyebrow">Content manager</span><h2>New gallery item</h2></div><button className="icon-button" onClick={() => setModal(false)}><X size={20} /></button></header><form onSubmit={save}>{form.src ? <div className="gallery-upload-preview"><Image src={form.src} alt="Upload preview" fill sizes="500px" /></div> : <label className="gallery-drop"><CloudUpload size={25} /><strong>{uploading ? `Uploading ${progress}%` : "Choose an image"}</strong><span>JPG, PNG or WebP · maximum 8 MB</span><input type="file" accept="image/*" onChange={(e) => choose(e.target.files?.[0])} disabled={uploading} /></label>}<div className="form-grid"><label className="field"><span>Title *</span><input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} required /></label><label className="field"><span>Category</span><select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}>{["Farm", "Animals", "Dairy", "Products", "Production", "Facilities", "Workers"].map((value) => <option key={value}>{value}</option>)}</select></label></div><p className="modal-help">Only upload media The Branch Farm owns or has permission to publish. AI imagery should be identified in its title or caption.</p><div className="modal-actions"><button type="button" className="button button-ghost" onClick={() => setModal(false)}>Cancel</button><button className="button button-primary" disabled={saving || uploading || !form.src}>{saving ? <i className="button-spinner" /> : "Publish item"}</button></div></form></div></div>}
  </div>;
}
